### ISSUE TITLE
hyprpicker stops working after a couple of uses

### ISSUE THREAD

**Issue by AmadeusWM** [hyprwm/hyprpicker#17]
In `hyprland.conf` I use a bind for `hyprpicker`:
```bash
bind=SUPER,C,exec,hyprpicker -a && notify-send --icon ~/.config/hypr/assets/blossom.png -u critical -t 4000 "$(wl-paste)"
```
It works for about 20 times. But then it suddenly breaks. When running hyprpicker in the terminal afterwards I get:
```bash
❯ hyprpicker
zsh: bus error (core dumped)  hyprpicker
```
Rebooting gets it working again. But then it breaks again, after a couple of uses.

I'm on AMD, and installed hyprpicker-git from the AUR.

**Comment by vaxerski** [comment]
coredump pls

**Comment by AmadeusWM** [comment]
Like this?
[coredump.txt](https://github.com/hyprwm/hyprpicker/files/10096047/coredump.txt)

**Comment by vaxerski** [comment]
https://github.com/hyprwm/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md

**Comment by AmadeusWM** [comment]
oh, I'm sorry. Here it is:
[coredump.txt](https://github.com/hyprwm/hyprpicker/files/10096406/coredump.txt)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/hyprpicker/files/10096787/patch.txt)

Can you try this patch?

clone hyprpicker, place the patch in the cloned repo, do
`patch -p1 < ./patch.txt`
and compile

**Comment by AmadeusWM** [comment]
after patching and compiling I tried spamming the command for a while. Using `hyprpicker` without the option `-a` seemed to work perfectly fine. But when using `hyprpicker -a` it breaks again after a couple of tries. 

Here you can see how many tries it took:
[output.txt](https://github.com/hyprwm/hyprpicker/files/10096839/output.txt)
And the coredump:
[coredump.txt](https://github.com/hyprwm/hyprpicker/files/10096838/coredump.txt)

If you need anything else, let me know. :D

**Comment by vaxerski** [comment]
can you compile hyprpicker in debug? this coredump is kinda garbled. (make debug)

**Comment by AmadeusWM** [comment]
Is this okay? (I did `make all debug`, because `make debug` gave an error. I hope that's what you meant)
Terminal output:
[output.txt](https://github.com/hyprwm/hyprpicker/files/10096894/output.txt)
Core dump in debug:
[coredump.txt](https://github.com/hyprwm/hyprpicker/files/10096895/coredump.txt)

**Comment by vaxerski** [comment]
`make all debug` is the same as `make all`. What error?

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/hyprpicker/files/10096984/patch.txt)

Try this patch.

**Comment by AmadeusWM** [comment]
> 
```bash
-- Generating done
-- Build files have been written to: /home/amadeusw/github-repositories/hyprpicker/build
cmake --build ./build --config Debug --target all -j 10
ninja: error: '/home/amadeusw/github-repositories/hyprpicker/wlr-layer-shell-unstable-v1-protocol.o', needed by 'hyprpicker', missing and no known rule to make it
make: *** [Makefile:57: debug] Error 1
```
I thing I'm missing a dependency, not sure which one. 
Thanks! I will try the patch rn.

**Comment by AmadeusWM** [comment]
> [patch.txt](https://github.com/hyprwm/hyprpicker/files/10096984/patch.txt)
> 
> Try this patch.

Same result, breaks after a couple of tries.
(This is still with `make all` btw):
[coredump.txt](https://github.com/hyprwm/hyprpicker/files/10097017/coredump.txt)

**Comment by vaxerski** [comment]
> I thing I'm missing a dependency, not sure which one.
You forgot to do `make protocols` before `make debug`. Coredumps with `make all` are useless.

**Comment by AmadeusWM** [comment]
Thank you for the patience, excuse my ignorance. :)
Now, I compiled with debug this time.

Coredump (debug):
[coredump-debug.txt](https://github.com/hyprwm/hyprpicker/files/10097516/coredump-debug.txt)

Output in terminal:
[terminal-output.txt](https://github.com/hyprwm/hyprpicker/files/10097517/terminal-output.txt)

**Comment by sroemer** [comment]
I just stumbled over `hyprpicker` and quickly compiled it. Nice and useful tool!
Then I saw this issue and quickly tried to replicate it. I see `hyprpicker -a` not working anymore after about 20 runs.

But the behaviour is slightly different in my case. I just see the message `wl_buffer@25: error 2: error accessing SHM buffer` in the terminal then. Maybe that helps in finding the cause of the issue.

**Comment by AmadeusWM** [comment]
> I just stumbled over `hyprpicker` and quickly compiled it. Nice and useful tool! Then I saw this issue and quickly tried to replicate it.
> 
> I also see `hyprpicker -a` not working anymore after about 20 runs, but the behaviour is slightly different in my case. I just see the message `wl_buffer@25: error 2: error accessing SHM buffer` in the terminal then. Maybe that helps in finding the cause of the issue.

I think it would help vaxry if you also produce a coredump (see above), thanks for the input :D

**Comment by sroemer** [comment]
@AmadeusWM: In my case this seems to be a controlled exit in case of an error which is handled somehow. There is no crash like in your case and therefore I cannot provide a coredump.

**Comment by sroemer** [comment]
I just had a short look into that again and made an additional observation:

$XDG_RUNTIME_DIR in my case gets filled up with lots of `.hyprpicker_XXXXX` (hidden) files. When the number of those files reaches 108 it does not work anymore (6 files each run seem to be generated). Calling `rm $XDG_RUNTIME_DIR/.hyprpicker_*` solved the issue and it worked again until it reached 108 files again.

So the problem seems to be that hyprpicker does not cleanup what it was writing and then somehow has a problem with those leftover files.

@AmadeusWM: Does manually cleaning up the XDG_RUNTIME_DIR  work for you as well?

**Comment by AmadeusWM** [comment]
> 

This indeed seems to fix the issue
Calling `rm $XDG_RUNTIME_DIR/.hyprpicker_*` makes `hyprpicker` work again.
Good observation!

**Comment by AmadeusWM** [comment]
I experience the same 6 files you were speaking of @sroemer 
```bash
❯ ls $XDG_RUNTIME_DIR -al | grep hypr
-rw-------  1 amadeusw amadeusw 41943040 27 nov 09:11 .hyprpicker_5cR2c9
-rw-------  1 amadeusw amadeusw 19814400 27 nov 09:11 .hyprpicker_71wKHO
-rw-------  1 amadeusw amadeusw 19814400 27 nov 09:11 .hyprpicker_k7dN1X
-rw-------  1 amadeusw amadeusw 19814400 27 nov 09:11 .hyprpicker_nX29ms
-rw-------  1 amadeusw amadeusw 16384000 27 nov 09:11 .hyprpicker_wxne6u
-rw-------  1 amadeusw amadeusw 41943040 27 nov 09:11 .hyprpicker_yuZkDV
❯ ./build/hyprpicker -a
#16151B
zsh: profile signal  ./build/hyprpicker -a
❯ ls $XDG_RUNTIME_DIR -al | grep hypr
-rw-------  1 amadeusw amadeusw 19814400 27 nov 09:11 .hyprpicker_3aQMyk
-rw-------  1 amadeusw amadeusw 41943040 27 nov 09:11 .hyprpicker_5cR2c9
-rw-------  1 amadeusw amadeusw 19814400 27 nov 09:11 .hyprpicker_71wKHO
-rw-------  1 amadeusw amadeusw 41943040 27 nov 09:11 .hyprpicker_cVSaQD
-rw-------  1 amadeusw amadeusw 19814400 27 nov 09:11 .hyprpicker_dm1llY
-rw-------  1 amadeusw amadeusw 19814400 27 nov 09:11 .hyprpicker_k7dN1X
-rw-------  1 amadeusw amadeusw 16384000 27 nov 09:11 .hyprpicker_l58NQ1
-rw-------  1 amadeusw amadeusw 19814400 27 nov 09:11 .hyprpicker_nX29ms
-rw-------  1 amadeusw amadeusw 19814400 27 nov 09:11 .hyprpicker_uzVOf3
-rw-------  1 amadeusw amadeusw 41943040 27 nov 09:11 .hyprpicker_WpeXw1
-rw-------  1 amadeusw amadeusw 16384000 27 nov 09:11 .hyprpicker_wxne6u
-rw-------  1 amadeusw amadeusw 41943040 27 nov 09:11 .hyprpicker_yuZkDV
```

**Comment by sroemer** [comment]
I had a look into the sources:

The problem is that `execlp()` which is called from within `Clipboard::copy()` never returns (this is the intended behavior of `execlp()` and in case of success the new process replaces the current process). For that reason the call of `g_pHyprpicker->finish()` at the end of `Events::handlePointerButton()` is not performed and therefore the cleanup does not happen.

**Comment by sroemer** [comment]
I did make a quite simple fix. Not the most elegant way for sure, but it does the job. See pull request https://github.com/hyprwm/hyprpicker/pull/18
