### ISSUE TITLE
Cachix?

### ISSUE THREAD

**Issue by rubyowo** [hyprwm/hyprpicker#23]
Could you add hyprpicker to cachix so that I don't have to build everytime? thanks

**Comment by vaxerski** [comment]
@fufexan

**Comment by fufexan** [comment]
All ready to go. It will be done when vaxry adds the cachix token to the repo.

**Comment by rubyowo** [comment]
Thanks!

**Comment by vaxerski** [comment]
added

**Comment by rubyowo** [comment]
it built. gonna close now
