### ISSUE TITLE
Formats

### ISSUE THREAD

**Issue by ThatOneCalculator** [hyprwm/hyprpicker#3]
Config file to choose default, flag at runtime to change

- Hex (default) (high priority)
- RGB(a) (high priority)
- HSL (mid priority)
- HSV (mid priority)
- CMYK (low priority)

**Comment by vaxerski** [comment]
hex and rgb in fb56dc68ca8a0e5b6f1eb3550b65bcb11e29c036

**Comment by Mango0x45** [comment]
HSL, HSV, and CMYK have been added in #12
