### ISSUE TITLE
segfault: Invalid stride (9023)

### ISSUE THREAD

**Issue by Kyohans** [hyprwm/hyprpicker#47]
I'm currently running `hyprland` and `hyprpicker` fails with the following error message:
```
[destroyed object]: error 1: Invalid stride (9023)
Segmentation fault (core dumped)
```
I am using EndeavourOS with a Surface Laptop 4 with the `linux-surface` kernel. I've noticed other issues mentioned having a Nvidia GPU but this appears to have been fixed since this works on my desktop which has a 3070ti.

**Comment by vaxerski** [comment]
that was fixed in hyprland 0.32.2
