### ISSUE TITLE
Error building git on Ubuntu 23.10

### ISSUE THREAD

**Issue by vaskark** [hyprwm/hyprpicker#60]
Until recently hyprpicker was building successfully. Now I'm getting this error during compilation:

> error: invalid argument '-std=c++23' not allowed with 'C'
> gmake[3]: *** [CMakeFiles/hyprpicker.dir/build.make:174: CMakeFiles/hyprpicker.dir/wlr-layer-shell-unstable-v1-protocol.c.o] Error 1
> gmake[3]: *** Waiting for unfinished jobs....
> 1 warning generated.
> gmake[2]: *** [CMakeFiles/Makefile2:83: CMakeFiles/hyprpicker.dir/all] Error 2
> gmake[1]: *** [CMakeFiles/Makefile2:90: CMakeFiles/hyprpicker.dir/rule] Error 2
> gmake: *** [Makefile:189: hyprpicker] Error 2

I'm using clang/clang++ 18.1 and Hyprland 0.36 (manual build copy). Any advice would be appreciated.
Thanks.

**Comment by vaxerski** [comment]
try gcc

**Comment by vaskark** [comment]
That did it. Many thanks.
