### ISSUE TITLE
Error while downloading hyprpicker via yay

### ISSUE THREAD

**Issue by MRPOZZIchanel** [hyprwm/hyprpicker#62]
So, I tried to install hyprpicker via yay and got an error:

make: entering directory "/home/padlakun/.cache/yay/hyprpicker-git/src/hyprpicker"
make: *** There is no rule for building the "all" target. Stop.
make: exit directory "/home/padlakun/.cache/yay/hyprpicker-git/src/hyprpicker"
==> ERROR: There was a failure in build().
    Interrupt...
 -> build error: hyprpicker-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
hyprpicker-git - exit status 4

Distro: Arch; Kernel: cachyos-bore 6.8.1-3

**Comment by vaxerski** [comment]
I don't maintain aur packages. Ask whoever does to fix it
