### ISSUE TITLE
[Feature Request] Show hex code below cursor/zoom lens

### ISSUE THREAD

**Issue by nktnet1** [hyprwm/hyprpicker#79]
Add an option to display the preferred format label, e.g. hex, below the zoom lens (or cursor) similar to Firefox's dev tool:

![image](https://github.com/hyprwm/hyprpicker/assets/86177399/1eb83f34-7d45-4d4a-8753-d16a11c9b90a)

**Comment by bun137** [comment]
Hey, I worked on this recently and opened a PR, let me know your suggestions! 
[Link to PR](https://github.com/hyprwm/hyprpicker/pull/95)

**Comment by danielwerg** [comment]
Similar to my https://github.com/hyprwm/hyprpicker/issues/56, should probably just expand on that.

**Comment by vaxerski** [comment]
ye, dup
