### ISSUE TITLE
Build issue with openGL on ARM64 target

### ISSUE THREAD

**Issue by dylad** [hyprwm/hyprpicker#80]
While trying to build hyprpicker from sources for an ARM64 target, link failed because openGL lib isn't supported by the target machine. If I remove the openGL dependency (but keep GLESv2), hyprpicker builds fine.
So I was wondering if the openGL feature could be optional at compile time ?

**Comment by vaxerski** [comment]
come to think of it, is GLES even required? hyprpicker isnt gpu accelerated IIRC.

**Comment by dylad** [comment]
At least, hyprpicker builds fine if I remove both openGL and GLESv2 from CMakeLists.txt

**Comment by vaxerski** [comment]
yeah I probably put those deps by accident

**Comment by dylad** [comment]
Should I open a PR to remove them ?

**Comment by fufexan** [comment]
Yes, please.
