### ISSUE TITLE
[Feature Request] Ignore Hyprland blur when picking colours

### ISSUE THREAD

**Issue by orxngc** [hyprwm/hyprpicker#84]
When picking colours in combination with Hyprlands blur and/or transparency feature, one doesn't pick the actual colour. It would be nice for hyprpicker to ignore the blur or transparency and only pick the colour.

**Comment by vaxerski** [comment]
?

**Comment by orxngc** [comment]
E.g. if I have a window open with a background set as #1e1e2e, window blur makes the actual pixels not that colour.. so using hyprpicker on it gives me #212231, for example. If it could ignore the window blur it would instead pick #1e1e2e

**Comment by vaxerski** [comment]
that is not possible
