### ISSUE TITLE
Monitor with rotation has scaling artifacts when using render-inactive

### ISSUE THREAD

**Issue by Beyley** [hyprwm/hyprpicker#91]
My right monitor has a rotation transform, and when hyprpicker's render-inactive feature it has very bad scaling artifacts (even though there's no display scaling set, so im assuming its scaling the captured frame according to the wrong dimensions, eg. `1280x1024` instead of `1024x1280`)

monitor info:
```
Monitor DP-3 (ID 1):
	1280x1024@75.02500 at 5360x120
	description: Dell Inc. DEL 1708FPBLK X876H92M1JRS
	make: Dell Inc.
	model: DEL 1708FPBLK
	serial: X876H92M1JRS
	active workspace: 11 (11)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.00
	transform: 1
	focused: no
	dpmsStatus: 1
	vrr: false
	solitary: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	availableModes: 1280x1024@60.02Hz 1280x1024@75.03Hz 1280x800@60.02Hz 1152x864@75.00Hz 1280x720@60.02Hz 1024x768@75.03Hz 1024x768@60.00Hz 800x600@75.00Hz 800x600@60.32Hz 640x480@75.00Hz 640x480@59.94Hz 720x400@70.08Hz 
```

example of the scaling artifacts
![image](https://github.com/user-attachments/assets/3a76f355-0e49-4c01-8510-53efe5bf8c36)

Problem goes away with `--no-fractional`, so that's my workaround for now

**Comment by sdooweloc** [comment]
I am also seeing this. The frustrating thing is if you use something like grimblast for your screenshots you cant pass the `--no-fractional` option to hyprpicker as the app doesnt support it and its realistically an upstream issue with how hyprpicker is handling things so I dont think it makes sense to submit an issue with each of the apps that hook into hyprpicker.

**Comment by vaxerski** [comment]
see #94
