### ISSUE TITLE
seg fault if mouse still

### ISSUE THREAD

**Issue by mbpowers** [hyprwm/hyprpicker#92]
hyprland 0.44.1-1
hyprpicker 0.4.1.r1.4411a6d-1
nvidia 560.35.03-15

hyprpicker segfaults if the mouse is still when run. any mouse movement at the moment it is started causes it to run as expected.

did a bisect and this was introduced in https://github.com/hyprwm/hyprpicker/commit/cbd963e1032552a7b195301de616c521c7d9f848. 

previous to that commit, when hyprpy is run the cursor jumps to the top left of the screen until the mouse is moved and then it jumps back. no segfault though

**Comment by vaxerski** [comment]
wat, I can't see how thats possible

**Comment by mbpowers** [comment]
figured out where its coming from. in my hyprland config I had
```
monitor = eDP-1,    preferred, 0x1110, 1
monitor = HDMI-A-1, preferred, 0x0,    1
```
which causes `getColorFromPixel(pSurface, CLICKPOSBUF)` to fail cause the mouse position is wrong. switching to the `auto` size syntax seems to avoid this.

**Comment by vaxerski** [comment]
odd but ok
