### ISSUE TITLE
Monitor image becomes pixelated/blurry on portrait monitors

### ISSUE THREAD

**Issue by mekb-turtle** [hyprwm/hyprpicker#96]
This shows on my monitor, but it affects screenshots that have been taken while hyprpicker is open, which is used to freeze the screenshot

Expected image:
![clean screenshot of text](https://github.com/user-attachments/assets/65d5d312-b60d-4468-af47-c291ba030d69)
![clean screenshot of repo name](https://github.com/user-attachments/assets/45b3316e-a293-4e7c-b758-a0484dffe3b2)

Actual image:
![pixelated screenshot of text](https://github.com/user-attachments/assets/1c0766fe-32b3-4cbd-815d-04df2a5fcde0)
![pixelated screenshot of repo name](https://github.com/user-attachments/assets/a1d2009a-b216-427d-979a-ba0b6c978b16)

I'm using Hyprland 0.45.0, with hyprpicker v0.4.1. I am on NVIDIA (nvidia-open 565.57.01-3) if that makes a difference.

**Comment by vaxerski** [comment]
can you try hyprpicker-git

**Comment by mekb-turtle** [comment]
issue goes away with -git
